package com.glassestore.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "glassestoredb")
@NamedQueries({
	@NamedQuery(name = "Review.listAll", query = "SELECT r FROM Review r ORDER BY r.reviewTime DESC"),
	@NamedQuery(name = "Review.countAll", query = "SELECT COUNT(r) FROM Review r"),
	@NamedQuery(name = "Review.findByCustomerAndGlasses", 
		query = "SELECT r FROM Review r WHERE r.customer.customerId =:customerId"
				+ " AND r.glasses.glasseId =:glasseId"),
	@NamedQuery(name = "Review.mostFavoredGlasse",
		query = "SELECT r.glasses, COUNT(r.glasses.glasseId) AS ReviewCount, AVG(r.rating) as AvgRating FROM Review r "
				+ "GROUP BY r.glasses.glasseId HAVING AVG(r.rating) >= 4.0 "
				+ "ORDER BY ReviewCount DESC, AvgRating DESC"),
	@NamedQuery(name = "Review.countByCustomer",
				query = "SELECT COUNT(r.reviewId) FROM Review r WHERE r.customer.customerId =:customerId")
})
public class Review {

	private Integer reviewId;
	private Glasses glasse;
	private Customer customer;
	private int rating;
	private String headline;
	private String comment;
	private Date reviewTime;

	public Review() {
	}

	public Review(Glasses glasse, Customer customer, int rating, String headline, String comment, Date reviewTime) {
		this.glasse = glasse;
		this.customer = customer;
		this.rating = rating;
		this.headline = headline;
		this.comment = comment;
		this.reviewTime = reviewTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id", nullable = false)
	public Glasses getGlasses() {
		return this.glasse;
	}

	public void setBook(Glasses glasse) {
		this.glasse = glasse;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "headline", nullable = false, length = 128)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "review_time", nullable = false, length = 19)
	public Date getReviewTime() {
		return this.reviewTime;
	}

	public void setReviewTime(Date reviewTime) {
		this.reviewTime = reviewTime;
	}

	@Transient
	public String getStars() {
		String result = "";
		
		int numberOfStarsOn = (int) rating;
		
		for (int i = 1; i <= numberOfStarsOn; i++) {
			result += "on,";
		}
		
		for (int j = numberOfStarsOn + 1; j <= 5; j++) {
			result += "off,";
		}
		
		return result.substring(0, result.length() - 1);
	}	
}
